/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "stm32f0xx.h"
uint32_t morse = 0b10101001110111011100101010000000;

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN; //enable clock
	GPIOA->MODER |= GPIO_MODER_MODER5_0; //PA5 as output mode 01

    while (1)
    {
      uint32_t morse = 0b10101001110111011100101010000000;
      for (uint8_t i = 0; i < 32-5; i++) //that -5 is there for removing last zeros...
      {
        if(morse & 0x80000000){//his works only because everything except 0 is true..
          GPIOA->BSRR = (1<<5); //SET PIN HIGH
        } 
        else{
        	GPIOA->BRR = (1<<5);
        }
        for (volatile uint32_t i = 0; i < 100000; i++){} //100k cycle delay
        morse = (uint32_t)morse << 1;
        //GPIOA->ODR ^= (1<<5);//toggle pin PA5

      }
    }
    
}
